export const types = {
  ADD_APPLICATION_REQUEST: "ADD_APPLICATION_REQUEST",
  ADD_APPLICATION_SUCCESS: "ADD_APPLICATION_SUCCESS",
  ADD_APPLICATION_FAILED: "ADD_APPLICATION_FAILED",

  GET_APPLICATION_REQUEST: "GET_APPLICATION_REQUEST",
  GET_APPLICATION_SUCCESS: "GET_APPLICATION_SUCCESS",
  GET_APPLICATION_FAILED: "GET_APPLICATION_FAILED",

  EDIT_APPLICATION_REQUEST: "EDIT_APPLICATION_REQUEST",
  EDIT_APPLICATION_SUCCESS: "EDIT_APPLICATION_SUCCESS",
  EDIT_APPLICATION_FAILED: "EDIT_APPLICATION_FAILED",

  UPDATE_APPLICATION_REQUEST: "UPDATE_APPLICATION_REQUEST",
  UPDATE_APPLICATION_SUCCESS: "UPDATE_APPLICATION_SUCCESS",
  UPDATE_APPLICATION_FAILED: "UPDATE_APPLICATION_FAILED",

  DELETE_APPLICATION_REQUEST: "DELETE_APPLICATION_REQUEST",
  DELETE_APPLICATION_SUCCESS: "DELETE_APPLICATION_SUCCESS",
  DELETE_APPLICATION_FAILED: "DELETE_APPLICATION_FAILED"
};
