export const URL_LOGIN = "/api/v2/login";
export const URL_PROFILE = "/api/v2/user/profil";
export const URL_REGISTER = "/api/v2/user/register";

export const types = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",

  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  PROFILE_FAILED: "PROFILE_FAILED",

  REMOVE_AUTH: "REMOVE_AUTH"
};
